from App import schemas
import pytest
from jose import jwt
from App.config import settings
from App.oauth2 import ACCESS_TOKEN_EXPIRE_MINUTES,ALGORITHM,SECRET_KEY


def test_create_user(client):
    res = client.post("/users/",json={"email" :"abc@gmail.com", "password" : "7890"} )

    new_user = schemas.UserOut(**res.json())  #It validates that the API response has the expected structure and data types.
    assert new_user.email == "abc@gmail.com"
    assert res.status_code == 201

#pytest → session fixture → client fixture → test executes → client fixture ends → session closes the database.

def test_login_user(client,test_user):
    res = client.post("/login", data={"username" : test_user["email"], "password" : "7890"})
    login_res = schemas.Token(**res.json())   #JWT created 
    payload = jwt.decode(login_res.access_token,settings.access_key, algorithms=[settings.algorithm])  #Decodes the JWT using the secret key. If the token is invalid, tampered with, or expired, it raises JWTError.
    id = payload.get("user_id")    #id = user_id inside JWT
    assert id == test_user["id"]   #test_user["id"] = actual user created in fixture
    assert login_res.token_type =="bearer"
    assert res.status_code == 200 

#So the jwt.decode() in your test is not required for the application to work. It's there to verify that the 
#JWT generated by the login endpoint contains the expected information. In the actual application, the 
#important decoding happens later, when a protected endpoint receives the token in the Authorization header.

# @pytest.mark.parametrize does not change fixture behavior. It simply creates multiple test invocations.
@pytest.mark.parametrize("email, password, status_code",[
    ("wrongemail@gmail.com", "7890", 403),
    ("rj@gmail.com" , "78900", 403),
    (None,"7890",422),
    ("rj@gmail.com", None, 422)
])

def test_failed_login(client,test_user,email,password,status_code):
    res = client.post("/login", data={"username" : email, 
                                    "password" : password})

    assert res.status_code == status_code  #403 = Auth refused    
    