name: Build and Deploy Code

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: testing

    env:
      DATABASE_HOST: postgres
      DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}

    services:
      postgres:
        image: postgres:16

        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DATABASE_NAME }}_test

        ports:
          - 5432:5432

        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest psycopg2-binary

      - name: Print environment
        run: |
          python - <<EOF
          import os
          print("DATABASE_HOST =", repr(os.getenv("DATABASE_HOST")))
          print("DATABASE_PORT =", repr(os.getenv("DATABASE_PORT")))
          print("DATABASE_NAME =", repr(os.getenv("DATABASE_NAME")))
          print("DATABASE_USER =", repr(os.getenv("DATABASE_USER")))
          EOF

      - name: Print Pydantic settings
        run: |
          python - <<EOF
          from App.config import settings
          print("HOST =", repr(settings.database_host))
          print("PORT =", repr(settings.database_port))
          print("DB =", repr(settings.database_name))
          print("USER =", repr(settings.database_user))
          EOF

      - name: Wait for PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

          until pg_isready -h postgres -p 5432 -U postgres
          do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Test database connection
        run: |
          python - <<EOF
          import psycopg2
          from App.config import settings

          conn = psycopg2.connect(
              host=settings.database_host,
              port=settings.database_port,
              database=settings.database_name + "_test",
              user=settings.database_user,
              password=settings.database_password
          )

          print("Database connection successful")
          conn.close()
          EOF

      - name: Run Tests
        run: pytest -v