name: Build and Deploy Codebase

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: testing

    env:
      DATABASE_HOST: postgres
      DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}

    services:
      postgres:
        image: postgres:16

        env:
          POSTGRES_USER: ${{ secrets.DATABASE_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DATABASE_NAME }}_test

        ports:
          - 5432:5432

        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest psycopg2-binary

      - name: Show Environment Variables
        run: |
          echo "DATABASE_HOST=$DATABASE_HOST"
          echo "DATABASE_PORT=$DATABASE_PORT"
          echo "DATABASE_NAME=$DATABASE_NAME"
          echo "DATABASE_USER=$DATABASE_USER"

      - name: Show Pydantic Settings
        run: |
          python - <<EOF
          from App.config import settings
          print("HOST:", settings.database_host)
          print("PORT:", settings.database_port)
          print("DB:", settings.database_name)
          print("USER:", settings.database_user)
          EOF

      - name: Install PostgreSQL Client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      

      - name: Test Database Connection
        run: |
          python - <<EOF
          import psycopg2
          from App.config import settings

          print("Connecting to database...")

          conn = psycopg2.connect(
              host=settings.database_host,
              port=settings.database_port,
              database=settings.database_name + "_test",
              user=settings.database_user,
              password=settings.database_password
          )

          print("Database connection successful!")
          conn.close()
          EOF

      - name: Run Tests
        run: |
          pytest -x -vv